package br.ufrn.imd.lip2.projeto;

public enum MaquinaDeEstado {
    INATIVO,
    AGUARDANDO_BEM_DESCRICAO,
    AGUARDANDO_BEM_NOME,
    AGUARDANDO_BEM_IDENTIFICADOR,
    AGURANDADO_BEM_CATEGORIA,
    AGUARDANDO_BEM_LOCALIZACAO,
    AGUARDANDO_LOCALIZACAO_NOME,
    AGUARDANDO_LOCALIZACAO_DESCRICAO,
    AGUARDANDO_CATEGORIA_NOME,
    AGUARDANDO_CATEGORIA_DESCRICAO,
    AGUARDANDO_CATEGORIA_IDENTIFICADOR,
    EMITIR_RELATORIO_BENS_POR_LOCAL;

}